// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/rmocchy/convinient_wire/sample/complex/handler"
	"github.com/rmocchy/convinient_wire/sample/complex/repository"
	"github.com/rmocchy/convinient_wire/sample/complex/service"
)

// Injectors from wire.go:

// InitializeUserApp はUserHandlerの依存関係を解決して初期化
func InitializeUserApp() (*UserAppSet, error) {
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	userAppSet := &UserAppSet{
		UserHandler: userHandler,
	}
	return userAppSet, nil
}

// InitializeOrderApp はProductHandlerとOrderHandlerの依存関係を解決して初期化
// - OrderServiceは2つのリポジトリに並列で依存
func InitializeOrderApp() (*OrderAppSet, error) {
	productRepository := repository.NewProductRepository()
	productService := service.NewProductService(productRepository)
	productHandler := handler.NewProductHandler(productService)
	userRepository := repository.NewUserRepository()
	orderService := service.NewOrderService(userRepository, productRepository)
	orderHandler := handler.NewOrderHandler(orderService)
	orderAppSet := &OrderAppSet{
		ProductHandler: productHandler,
		OrderHandler:   orderHandler,
	}
	return orderAppSet, nil
}

// wire.go:

// @cire
// UserAppSet はUserHandlerを持つルート構造体
type UserAppSet struct {
	UserHandler *handler.UserHandler
}

// @cire
// OrderAppSet はProductHandlerとOrderHandlerを持つルート構造体（並列依存の例）
type OrderAppSet struct {
	ProductHandler *handler.ProductHandler
	OrderHandler   *handler.OrderHandler
}
