// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rmocchy/convinient_wire/sample/complex/handler"
	"github.com/rmocchy/convinient_wire/sample/complex/repository"
	"github.com/rmocchy/convinient_wire/sample/complex/service"
)

// Injectors from wire.go:

// InitializeUserApp initializes UserApp with all dependencies
func InitializeUserApp() (*UserApp, error) {
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	userApp := &UserApp{
		UserHandler: userHandler,
	}
	return userApp, nil
}

// InitializeOrderApp initializes OrderApp with all dependencies
func InitializeOrderApp() (*OrderApp, error) {
	productRepository := repository.NewProductRepository()
	productService := service.NewProductService(productRepository)
	productHandler := handler.NewProductHandler(productService)
	userRepository := repository.NewUserRepository()
	orderService := service.NewOrderService(userRepository, productRepository)
	orderHandler := handler.NewOrderHandler(orderService)
	orderApp := &OrderApp{
		ProductHandler: productHandler,
		OrderHandler:   orderHandler,
	}
	return orderApp, nil
}

// wire.go:

// UserAppSet is the Wire provider set for UserApp
var UserAppSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, handler.NewUserHandler, wire.Struct(new(UserApp), "*"))

// OrderAppSet is the Wire provider set for OrderApp
var OrderAppSet = wire.NewSet(repository.NewProductRepository, service.NewProductService, handler.NewProductHandler, repository.NewUserRepository, service.NewOrderService, handler.NewOrderHandler, wire.Struct(new(OrderApp), "*"))
